### ISSUE TITLE
HCA attack not covered in AE generation logic

### ISSUE THREAD

**Issue by maximcherny** [aldahdooh/detectors_review#1]
Hi!

First and foremost thanks for releasing the source code for this paper!

I have been going through the stages with the intention of replicating the setup locally, however it seems that there may possibly be logic portions missing, specifically in relation to generating AEs using the HCA attack.

For instance, running the NCI detector following model and AE generation results in (paths redacted):

```
Traceback (most recent call last):
  File "detect_nic.py", line 779, in <module>
    main(args)
  File "detect_nic.py", line 128, in main
    (adv_data_dir, args.dataset, attack))
  File "/Users/***/.virtualenvs/detectors/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/***/detectors_review/adv_data/mnist_hca_0.3125.npy'
```

Also, looking at `generate_adv.py` there appears to be no mention of the HCA attack in the associated code - other than having the `CarliniL2Method` attack included with the hard-code confidence parameter value of 10.

**Comment by aldahdooh** [comment]
Hi @maximcherny, Thanks for your interest, and sorry for the late replay. 
for high confidence attack I used the one that is implemented [here](https://github.com/anishathalye/obfuscated-gradients/blob/master/lid/lid.ipynb).
