### ISSUE TITLE
Is there files missing in FS detection method?

### ISSUE THREAD

**Issue by PoseidomWong** [aldahdooh/detectors_review#2]
for example, in /detectors/fs/datasets/datasets_utils.py, there need visualization.py file though it doesn't being used there, it's been used in other places. Many other files are missing too in FS, could you upload them? Thank you.

**Comment by aldahdooh** [comment]
Hi @PoseidomWong 
Sorry for the late reply. I only included, in my work, what is necessary to run the detectors. If you need any "utils" files or functions from other detectors, you can refer to the corresponding original repository of the detectors (I included them in the README file).
